version: '2'
services:
  postfix:
    hostname: postfix
    container_name: postfix
    build: .
    image: docker-ubuntu-postfix
    ports:
      - "8025:8025"
    #environment:
     # - "SUPERVISORD_LOGLEVEL=debug"
